### PR TITLE
ADD optional condition #28

### PR DESCRIPTION
**Pull request by tetienne**

### CODE REVIEW

**Comment by tetienne** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/somfy-open-api/somfy-open-api/pullRequest?prid=4537779&bid=15273702)

**Comment by tetienne** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/somfy-open-api/somfy-open-api/pullRequest?prid=4537779&bid=15273702)

**Comment by vlebourl** [comment]
with this branch, all getters on the thermostat are now working as expected.

**Comment by tetienne** [comment]
@vlebourl You are pretty fast to check :) Thx.

**Pull request merged**
